name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Cache node modules
      uses: actions/cache@preview
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: yarn install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        yarn install
        
    - name: yarn lint
      run: |
        yarn lint

    - name: Build Release
      if: github.ref == 'refs/heads/master'
      run: |
        yarn dist

    - name: GH Pages Publish
      uses: maxheld83/ghpages@v0.2.1
      if: github.ref == 'refs/heads/master'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: "dist/"
